name: Workflows, Jobs, and Steps

on:
  workflow_dispatch:
jobs:
  job-1:
    name: job-1
    runs-on: ubuntu-24.04
    steps:
      - name: echo 1
        run: |
          echo "A job consists of"
          echo "one or more steps"
          echo "which run sequentially"
          echo "within the same compute environment"

  job-2:
    name: job-2
    runs-on: ubuntu-24.04
    steps:
      - name: echo 2
        run: echo "Multiple jobs can run in parallel"

  job-3:
    name: job-3
    runs-on: ubuntu-24.04
    needs:
      - job-1
      - job-2
    steps:
      - name: echo 3
        run: echo "Jobs can depend on one another..."
      
  job-4:
    name: job-4
    runs-on: ubuntu-24.04
    needs:
      - job-2
      - job-3
    steps:
      - name: echo 4
        run: echo "...to form a directed acyclic graph (DAG)"
